server:
  port: 8080

---
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    test-on-borrow: true
    validation-query: SELECT 1 FROM dual
  flyway:
    baselineOnMigrate: true
    user: postgres
    password: 1234
    schemas: public
    createSchemas: true
    locations: db/migration, db/specific/h2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format-sql: true

  messages:
    basename: i18n/messages

  springdoc:
    api-docs:
      enable: true
  swagger-ui:
    enabled: 'true'
    path: /doc/swagger-ui.html